### ISSUE TITLE
how can I let the tv to play the another http server 's file ,like  the http://aaa.com/a.mp4

### ISSUE THREAD

**Issue by qbgit** [alexballas/go2tv#10]

**Comment by alexballas** [comment]
Hello,
Go2TV current does not support remote file play. Only local files. Certainly a nice feature to include.

**Comment by alexballas** [comment]
Started working on this one on the following branch [feature/support_external_urls](/alexballas/go2tv/tree/feature/support_external_urls)
Aiming to include it in the next version (1.9)

**Comment by alexballas** [comment]
This functionality is now available in the [latest release](https://github.com/alexballas/Go2TV/releases/latest)
