### ISSUE TITLE
[LG WebOS] Forward and backwards

### ISSUE THREAD

**Issue by SSadistic** [alexballas/go2tv#18]
Can you add the ability for forward and backwards, because it's saying that's currently disabled. But with other dlna servers its working, so i know it's something here. Other than that this program is nearly perfect.

**Comment by alexballas** [comment]
Hello,

Thanks for raising this! 
I tried to replicate this bahaviour as per the video below but it works fine with my Samsung TV.

https://user-images.githubusercontent.com/11015965/132981291-d506b968-d829-4f04-b01f-e50433db3024.mp4

I've googled a bit and saw similar reported issues with some LG tvs. 
LG issue asside, I do agree that more control from inside the app would be better but I first need to confirm a few things with regards to the implementation and flows.

Leaving this one open for further investigation.

**Comment by alexballas** [comment]
@SSadistic would it be possible to share whick DLNA servers you used to test this and worked? I suspect this issue has to do with some special headers passed to the http server that serves the content. If I at least confirm this, I could propose a change but I would still require your assistance to test it as I dont own a LG webOS TV.

**Comment by SSadistic** [comment]
SimpleDLNA is the simplest which is working with my TV, Universal Media Sever is more complex, it also works. I liked SimpleDLNA and used it before this, the problem is that SimpleDLNA doesn't load subtitles.

**Comment by alexballas** [comment]
I pushed some changes to the following branch https://github.com/alexballas/go2tv/tree/bugfix/improve_dlna_headers_logic
Also built some developement versions for you to test if you're unable to build it from the code.
Let me know if these changes did the trick.

[go2tv_v1.7_devel_windows_amd64.zip](https://github.com/alexballas/go2tv/files/7163658/go2tv_v1.7_devel_windows_amd64.zip)
[go2tv_v1.7_devel_linux_amd64.zip](https://github.com/alexballas/go2tv/files/7163659/go2tv_v1.7_devel_linux_amd64.zip)

**Comment by SSadistic** [comment]
![IMG_20210914_201206.jpg](https://user-images.githubusercontent.com/4640551/133303210-8e40d49a-57b2-41de-8b27-9bc06058f613.jpg)

Same, can't again.. the volume option is nice though. Also yes, i cannot compile myself, don't have the tools, so thanks for building.

**Comment by alexballas** [comment]
Oh that's unfortunate. I need to get my hands on one of those TVs to run my checks. So I'll keep it open for now.
Yes, the mute functionality will be available in the next version release.

**Comment by SSadistic** [comment]
You can see SmartShare which is the official LG dlna app,but I don't think the source is somewhere in the wild.

**Comment by alexballas** [comment]
Hey @SSadistic. So I was still not able to get my hand on LG WebOS TV. What would really be helpful is to sniff the HTTP traffic with wireshark when streaming the videos and specifically the value of the "contentFeatures.dlna.org" header.

What I'm looking is to have a look at what your LG sends and what it expects from one of the working DLNA servers you pasted above, like the Universal Media Sever or SimpleDLNA.

My investigation is focused around the "contentFeatures.dlna.org" header. I'll do some more investigation to see if I'm missing something on the protocol side.

The post from the emby.media forum looks interesting but it's a bit cryptic.

**Comment by alexballas** [comment]
Also in the Emby forum they mention about the DTS audio codec. Can you please test with a video file that has NO audio at all like the following video sample?

https://user-images.githubusercontent.com/11015965/136700078-908c4b17-54d0-4253-96f4-e48dc0fc5729.mp4

**Comment by alexballas** [comment]
Been few months since we last touched this one but unfortunately I was not able to find a LG to test. However I did push various protocol improvements to the development branch that are not released yet. Would it be possible to give it a try?
[go2tv_devel.zip](https://github.com/alexballas/go2tv/files/8935499/go2tv_devel.zip)

**Comment by SSadistic** [comment]
Right now I'm not in my home country, i can test it but somewhere at the end of the month

**Comment by alexballas** [comment]
No problem! Thanks for that! Let me know when you tested it!

**Comment by SSadistic** [comment]
> No problem! Thanks for that! Let me know when you tested it!

Hello. Today I tested it and it's indeed working as it should be, I can use rewinding and forwarding and it's now this is a perfect (for me) solution for watching films on my TV.

**Comment by alexballas** [comment]
At last! Great news! Thank you! I'll include all changes in the next release!

**Comment by alexballas** [comment]
Fixed with 1.12.0, resolving
