### ISSUE TITLE
[Android] File name not showing correctly.

### ISSUE THREAD

**Issue by SSadistic** [alexballas/go2tv#25]
Hello,

The android app is a good addition, but it doesn't show the name of the file properly on Phone and TV.
![Screenshot_20211130-063036.jpg](https://user-images.githubusercontent.com/4640551/143986192-dabd3463-ea5a-4e39-9267-2058a3255c0f.jpg)

**Comment by alexballas** [comment]
Thanks for raising this! Not sure how I missed it. I pushed a fix in the development branch and should be available in the next release.

**Comment by alexballas** [comment]
fixed in v1.9.1
