### ISSUE TITLE
Running as server like MPD

### ISSUE THREAD

**Issue by empirefox** [alexballas/go2tv#26]
Any plans?

**Comment by alexballas** [comment]
Hey @empirefox, would it be possible to elaborate a bit on this? Go2TV casts media files directly to the selected devices that support the Direct Media Renderer service without any actions on the device itself. So there needs to be some form of application trigger to push those contents to the devices. 

There are other applications like miniDLNA or MediaTomb that offer you a content **server** which you can browser from your TV or other devices. Is this what you're suggesting?

On a different note, the CLI option in Go2TV is quite versatile. You can have it running in the background, looping over media folders.
```bash
screen -d -m bash -c 'for q in ~/Videos/*mp4;do go2tv -v "$q";done'
```
This command for example will run in the background and start casting all your .mp4 files one after another

**Comment by empirefox** [comment]
Thanks @alexballas. I just want to running a MPD-like server on a pi. Then I could make a flutter app to control it from my phone.

**Comment by alexballas** [comment]
The API is now exported and anyone can import the go2tv code to their applications and introduce this functionality. I don't plan to make this part of the Go2TV code so I'm closing this issue.
