### ISSUE TITLE
Possible device naming bug

### ISSUE THREAD

**Issue by 4cecoder** [alexballas/go2tv#28]
No device name bug
Device Philips TV

Device Info in gui: 
UPnP/1.0  AwoX/1.1

**Comment by alexballas** [comment]
Thanks for raising this. Will have a look. Not sure if it's going to be straightforward however.

**Comment by alexballas** [comment]
Pushed a fix here -> https://github.com/alexballas/go2tv/commit/adba87e496919b909f64464d9c0314f5681407dc
Should be available in the next patch release

**Comment by alexballas** [comment]
fixed in v1.9.1
