### ISSUE TITLE
As a gui user: I want to move a slider that controls seeking on the device media is casted to

### ISSUE THREAD

**Issue by 4cecoder** [alexballas/go2tv#30]

**Comment by alexballas** [comment]
Sorry for the delay on this one. Yes this is would be nice to implement but as a functionality I expect it to be fairly limited. Not all devices implement the seek functionality in a very similar way.

**Comment by alexballas** [comment]
Currently working on this. It should be available in the upcoming versions

**Comment by alexballas** [comment]
This is now available in the latest versions. Resolving
