### ISSUE TITLE
make internal pkg public，so others can use this to make some other go pkg

### ISSUE THREAD

**Issue by chyroc** [alexballas/go2tv#34]

**Comment by chyroc** [comment]
and，add error callback ，not is.exit，to handle error better

**Comment by chyroc** [comment]
if you think this is good，i well make a pr to do change

**Comment by alexballas** [comment]
Yes, this is a very nice idea. It's something that I also wanted to do but kept prioritizing other features. This will also help with requests like https://github.com/alexballas/go2tv/issues/26

As for the go2tv CLI mode where various errors will trigger a os.Exit, I think it's OK for the specific mode. What we could do is wrap the main function to a "Run() error" like cobra does it and call that from main.

**Comment by chyroc** [comment]
remove internal package work in https://github.com/alexballas/go2tv/pull/35

**Comment by alexballas** [comment]
Thank you. Just a few notes. 
- I don't believe that we should remove everything from the "internal" folder. Things like the GUI or the Interactive CLI terminal should remain in the internal folder as these are specific to the go2tv application and it's not something that others could easily re-use
- Making things public will need some better documentation for the exported items. (we might need a separate ticket for that)

**Comment by alexballas** [comment]
Pushed a commit here https://github.com/alexballas/go2tv/commit/4ae40961604a7c7fdd191ca669bf5479da6edd59

**Comment by alexballas** [comment]
Nothing else to do here
