### ISSUE TITLE
add TvControl to define how to render tv control ui

### ISSUE THREAD

**Issue by chyroc** [alexballas/go2tv#36]
define TVControl interface to define how to render tv render ui,

i define the terminal ui:

by package :
```
	"github.com/eiannone/keyboard"
	"github.com/gosuri/uilive"
```

- keyboard to listen keyboard input, to do pause, play, volume add ...
- uilive to show text to terminal and refresh it(not add)

![image](https://user-images.githubusercontent.com/15604894/154827465-86ad00a0-a9b1-40f4-875b-5a90b25d4262.png)
![image](https://user-images.githubusercontent.com/15604894/154827470-837da675-877a-4f0a-966b-1866e46b382d.png)

and ,`go2tv` define two TvControl: one gui and one NewScreen

NewScreen is a full screen termianl console, I don't like full screen very much (or in some scenarios, full screen is too big)

**Comment by alexballas** [comment]
Thanks for raising this one. Few questions from me.
- What's the benefit of using ```	"github.com/eiannone/keyboard"``` and ```"github.com/gosuri/uilive"``` over tcell?
- How would you model this TvControl interface? Could you please share some examples?

**Comment by alexballas** [comment]
No feedback, resolving this for now.
