### ISSUE TITLE
wireguard

### ISSUE THREAD

**Issue by heptagons** [alexballas/go2tv#42]
Having wireguard service running in my linux I got a:
```
$ go run cmd/go2tv/go2tv.go -l
Encountered error(s): checkflags error: checkTflag service loading error: LoadSSDPservices search error: write udp 0.0.0.0:55145->239.255.255.250:1900: sendmsg: required key not available
exit status 1
```
Only disabling wireguard with `sudo wg-quick down wg0`  my TV was detected and go2tv worked OK.

How to have wireguard and SSDP at the same time?
Good job with go2tv!

**Comment by alexballas** [comment]
Hello!

SSDP relies on multicast traffic. To what I've seen with a quick search, you need to explicitly configure your WG setup to handle this type of traffic. I found this guide https://an0n-r0.medium.com/making-dlna-through-site-to-site-vpn-work-f393629f4ce0 online but I haven't tested it personally. This article addresses a different issue where someone is trying to access a DLNA server (which also relies on SSDP) remotely through WG, but it should give you an idea where to further look at.

Let me know if you have any other question.

Regards,
Alex

**Comment by heptagons** [comment]
Thanks. I'll check the guide.

1. The error I got is displayed in console mode. It should be nice to notify the error also in GUI instead of an empty list.
2. Forgive my ignorance. Is TVs discovery only possible with SSDP? What about [ZeroConf](https://github.com/grandcat/zeroconf)?

Regards

**Comment by alexballas** [comment]
For 1)
You're right. There should be an error message to indicate inability to pull the device list. I'll improve it in the next version.

For 2)
What go2tv does is use a subset of the DLNA/uPnP specification which is something that all smart TVs and some Audio speakers support. This is described here https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v1.1.pdf and
SSDP is part of that protocol. It's the actual devices (TV/Speakers) that use SSDP to publish their capabilities to the rest of the network. Go2TV just looks for those.

Zeroconf is an implementation of the Multicast DNS-SD protocol. There are other protocols in the wild like the castv2 that chromecast devices use. Castv2 uses mDNS-SD as per it's specification.
Unfortunately go2tv does not support chromecast devices as also mentioned in https://github.com/alexballas/go2tv/issues/38

**Comment by be-neth** [comment]
Hi,

I have the same issue, but unfortunately stopping wg-quick does not change this error message.
I have go2tv version :

```
go2tv  -version
Go2TV Version: 1.11.0
```

```
go2tv -l
Encountered error(s): checkflags error: checkTflag service loading error: loadSSDPservices: No available Media Renderers
```

**Comment by alexballas** [comment]
I'll resolve this one for now. I added an extra check in the GUI mode to properly reflect these "unwanted" errors, like we do in the CLI mode
