### ISSUE TITLE
The Chinese display is not normal in the interface.

### ISSUE THREAD

**Issue by duolabmeng6** [alexballas/go2tv#52]
![image](https://user-images.githubusercontent.com/59047063/181601667-9a6a5e91-5ebf-40bf-a675-76eb64b39213.png)

**Comment by alexballas** [comment]
Hello! 
Thank you for raising this. 

Go2TV GUI is based on the Fyne (https://github.com/fyne-io/fyne) toolkit. Fyne only bundles the NotoSans font which does not include Chinese or other Asian characters).

Can you please try specifying the path to a Chinese TTF file in the FYNE_FONT environment variable?
This should correct the display of the characters.

Another approach could be to inject a Chinese font into the Go2TV app with code but that would only partially fix the issue since then we should also include other fonts like Bengali and Japanese etc… and they are huge.

Thanks,
Alex

**Comment by duolabmeng6** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/59047063/181679612-ddf83555-2ccc-4538-8bd2-f4508976aa0f.png">

Thank you very much.

**Comment by duolabmeng6** [comment]
https://github.com/flopp/go-findfont

```
func init() {
	fontPaths := findfont.List()
	for _, path := range fontPaths {
		fmt.Println(path)
		//楷体:simkai.ttf
		//黑体:simhei.ttf
		if strings.Contains(path, "simkai.ttf") {
			os.Setenv("FYNE_FONT", path)
			break
		}
	}
	fmt.Println("=============")
}
```

**Comment by alexballas** [comment]
> However, for volume control, there is no way to restore sound on Huawei's smart screen.
Could you please some more details on this? What's not working?

**Comment by duolabmeng6** [comment]
> > However, for volume control, there is no way to restore sound on Huawei's smart screen.
> 
> Could you please some more details on this? What's not working?

Product model: 华为智慧屏 s65
https://www.vmall.com/product/10086874753382.html

problem


<img width="798" alt="image" src="https://user-images.githubusercontent.com/59047063/181846062-0695d3a3-c78f-4ee1-93ef-997671c7b996.png">
The video is displayed normally. It is normal to add or subtract the volume when it is not muted.
I think it's the TV set of Huawei. The volume cannot be restored after muting
If you don't mute, it's normal to increase or decrease the volume.

**Comment by alexballas** [comment]
But if you click it again and the sound is unmuted, the volume controls start working again? Correct?

**Comment by duolabmeng6** [comment]
> But if you click it again and the sound is unmuted, the volume controls start working again? Correct?

I mean, after muting, the software can't restore the sound. You have to use the remote control.

**Comment by duolabmeng6** [comment]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/59047063/181995188-a09c86af-a2ec-4d41-b772-2cb9769b8bff.png">

Can't return data under window. I think it's your gui..

So I made a magic change.

**Comment by duolabmeng6** [comment]
https://github.com/duolabmeng6/easy_to_tv

Because your gui is so hard to use.. I specially wrote a new one for myself to use.


About the problem that data cannot be returned under window
What I did was to delete all the code for gui and terminal interaction.

https://github.com/duolabmeng6/easy_to_tv/blob/main/go2tv_res/cmd/go2tv-lite/go2tv.go

Thank you for the code. Thank you very much. Although my writing is not perfect, it really works.

**Comment by alexballas** [comment]
So after muting, umuting does not work. That's really strange since both Mute and Unmute work on the same way.
As for the GUI, that's fine. I understand not many people like it. This is why I have the go2tv-lite.

**Comment by duolabmeng6** [comment]
It's okay. It could be Huawei's problem.
