### ISSUE TITLE
dv files

### ISSUE THREAD

**Issue by plegrand1** [alexballas/go2tv#54]
Hello,
thank you for this great application that works perfectly.
I had a small question: 
How should I proceed to play ".dv" files created by a digital camera?
Do I have to convert them first?
Or the application, via an option, would be able to play them?
Thanks for your help
Pascal

**Comment by alexballas** [comment]
Hello!
Thanks for that.
The playback support of all media files and formats depends on the target device. So if your device supports the dv format, it should be able to play it.

Go2TV has two interfaces, one GUI and one CLI (command line). In the GUI interface I had to hardcode the supported file types to make it easier for the users to navigate through the files. Unfortunately the dv file type was not included but it's certainly something I could add in a future release. On the other hard, the CLI interface is a bit more loose with those file type checks, so you can easily do `go2tv -v youfile.dv` and see if you device is able to play the file. 
If your device does not support it, you can try the "transcoding" functionality (the "-tc" flag), assuming you have ffmpeg installed in your system.

Hope that helps.
Thanks,
Alex

**Comment by alexballas** [comment]
Included this in the latest v1.13.0 release. Resolving
