### ISSUE TITLE
[Request] Add program projection function and browser page projection function

### ISSUE THREAD

**Issue by Carlos920** [alexballas/go2tv#60]

**Comment by alexballas** [comment]
Hello, apologies but the request is not very clear. Could you please elaborate?

**Comment by alexballas** [comment]
Closing this for now until further details are provided.

**Comment by Carlos920** [comment]
1. Cast the page you are browsing in the browser to the TV
2. Cast open app interface to TV

**Comment by alexballas** [comment]
Thank you. Unfortunately this is not possible. The reason was explained in https://github.com/alexballas/go2tv/issues/51
TL;DR:
UPNP is not the right protocol to handle this type of streaming. You could potentially workaround it but that implementation would be janky
