### ISSUE TITLE
Playing from NAS folder (SMB share) on MacOS

### ISSUE THREAD

**Issue by michael-wenyon** [alexballas/go2tv#67]
Go2TV GUI on MacOS, the graphic file browser does not let me 'see' my NAS server or its folders (SMB sharing).

To see it in the MacOS finder I make invisible folders visible and the sharepoint can be found in the /Volumes folder. But in the Go2TV file browser the 'Computer' does not have a visible /Volumes folder, and I don't see a way to make it visible. How can I get to the files I want to play on my NAS?

**Comment by alexballas** [comment]
Hello @michael-wenyon,

That's strange. The file picker should have access to the /Volumes folder. I'm not a Mac user myself so I can't confirm this behavior right away. Can you please also double check that you provided all the required permissions to the application? Please refer to https://support.apple.com/guide/mac-help/control-access-to-files-and-folders-on-mac-mchld5a35146/mac

Thanks,
Alex

**Comment by alexballas** [comment]
The "media" folder seems to have all the right permissions, so it should show up. Could it be that it's taking some time to load? If you run go2tv from the terminal, do you get any errors when trying to list he /Volumes content?

**Comment by michael-wenyon** [comment]
I don't have a CLI for Go2TV on MacOS, only the GUI.

```
michael@grey ~ % go2tv
zsh: command not found: go2tv
```

**Comment by NickDunas** [comment]
I just created a shared folder on my windows 10 PC and I can see the folder and all sub-folders just fine through go2tv.

**Comment by alexballas** [comment]
Resolving as we could not replicate this.
