### ISSUE TITLE
Always Wating for status

### ISSUE THREAD

**Issue by mostcute** [alexballas/go2tv#68]
i use go2tv to play the video to my JMGO-N1 Ultra Projector using

`./go2tv -v 1.mkv -t   http://192.168.123.34:49152/description.xml`

![image](https://github.com/alexballas/go2tv/assets/23225426/c78a4591-f3b8-446e-b10c-f314e774d959)

every thing is ok,the video playing well and i can use keyboard to control the volume,but the status is always ` waiting for status `not `Playing`

**Comment by mostcute** [comment]
i use the master branch to build

**Comment by mostcute** [comment]
git branch -vv 

```
main 86a7b6c
```

**Comment by mostcute** [comment]
i check the code,find  the callback handler will change the `status` state, maybe this is the devices's problem that did'nt call the callback function to update the state?

**Comment by alexballas** [comment]
Hello, thanks for raising this. 
That is correct. It's the device that is responsible to provide an event URL for Go2TV to subscribe to and receive all notifications from that device.
The GUI mode provides an "Export Debug Logs" option which would be useful to check. Would it be possible to try to play you file though the GUI mode and then export the logs and paste them here?

**Comment by mostcute** [comment]
[debug.log](https://github.com/alexballas/go2tv/files/11634760/debug.log)


here, i use the gui play the video and test the function mute, volume add/dec drag the progress

**Comment by mostcute** [comment]
[debug2.log](https://github.com/alexballas/go2tv/files/11634774/debug2.log)

more log,i clieck the play button,it will be pause button secons later, but if i click the pause buttun, it won't be play buttin again.

which means i can't replay the paused video unless i click stop button

**Comment by alexballas** [comment]
> more log,i click the play button,it will become pause button seconds later, but if i click the pause buttun, it won't be play button again.
> 
> which means i can't replay the paused video unless i click stop button
Yes, this is because there is no callback from the device so the application is re-enabling the buttons after a few seconds. However this auto-enable functionality is not perfect and I'll try to improve it in the next release. 
I had a quick look at the logs but I dont see any apparent errors. The device just refuses to cooperate.
Do you happen to have a smart tv or other device to test it too?

**Comment by mostcute** [comment]
When I pause and play using the device's remote control, the status of the GUI still cannot be synchronized due to no callback. But this is no longer something that this software can solve

**Comment by alexballas** [comment]
I might drop the delay to 3 seconds.
Btw you can try to compile a version of Go2TV where parseProtocolInfo always returns nil. So in theory you could try to play some sound to your speaker without this limitation

**Comment by mostcute** [comment]
yes ,that works!  the speaker can play the mp3 and mp4

**Comment by alexballas** [comment]
Does the callback functionality work for the smart speaker?

**Comment by mostcute** [comment]
yes ,the speaker seems call the callback because the button change state immediately

**Comment by alexballas** [comment]
Closing as there is nothing further to do here. Some improvements around Protocol info parsing will be included in the upcoming release.
