### ISSUE TITLE
How to stream youtube video ?

### ISSUE THREAD

**Issue by techgamers2** [alexballas/go2tv#71]
i tried pasting video url and video download url ( captured by idm ) both didnt worked

**Comment by alexballas** [comment]
Hello @techgamers2, URL streaming only accepts direct videos / image / audio files served through HTTP, not services like youtube where the video file itself is hidden or needs to be extracted in a specific way (for example youtube-dl)

If you need to stream youtube videos, there is a different protocol in place to do that. This protocol is called DIAL and it's not something Go2TV supports. This protocol is responsible for triggering the applications like YouTube, Netflix, Spotify that are installed in the devices, launching them and controlling them. https://github.com/MarcoLucidi01/ytcast is a tool that implements this protocol.

**Comment by techgamers2** [comment]
thanks for fast response ok i understand ... gui is easier to use than commandline hope this feature gets implemented in future... also i like ur go2tv app as my inbuilt windows cast feature is broken tried many fix but nothing helped so i tried ur app and it helped me ty for tht

**Comment by alexballas** [comment]
Thanks for that :). The DIAL protocol is something that I'm considering adding but I still need to figure out how to make it as user friendly as possible. In the meantime I'll close this issue. Feel free to raise a new one if you have any issues or questions.
- Alex

**Comment by alexballas** [comment]
With the latest release you can now pipe youtube videos into go2tv. Please refer to the README.md
