### ISSUE TITLE
Support for DSF?

### ISSUE THREAD

**Issue by andrewgdunn** [alexballas/go2tv#73]
Would it be possible to support DSF?

**Comment by alexballas** [comment]
Hello and thanks for raising this.  
Support for formats like DSF or any other depends 100% on the target device. If the device supports it, it should work with Go2TV too.
It's true that currently the GUI mode does allow you to select DSF files but that would be easy to add in future releases. However you can still play those files in the CLI mode by calling
```
go2tv -v yourfile.dsf
```
Thanks,
Alex
