### ISSUE TITLE
Chinese Directory display problem

### ISSUE THREAD

**Issue by xiaohelong** [alexballas/go2tv#75]
Chinese language named Directory display problem,not correct,please add this support.

**Comment by alexballas** [comment]
Hello @xiaohelong,
Thanks for taking the time to raise this issue. The Chinese language issue was also raised here https://github.com/alexballas/go2tv/issues/52#issuecomment-1198506691
can you please refer to my comment and let me know if the workaround works for you?

Regards,
Alex
