### ISSUE TITLE
The latest released zip on windows cannot run on windows7 system

### ISSUE THREAD

**Issue by lllAlex2333** [alexballas/go2tv#82]
The latest released zip(go2tv_v1.16.0_windows_amd64.zip) on windows cannot run on windows7 system.
I tried to recompile using a lower version of go environment, but it failed.
Do you have any other solutions? Thanks!

**Comment by alexballas** [comment]
Hello, thanks for raising this. This looks like the same issue as https://github.com/alexballas/go2tv/issues/29
Can you please enable the 3D acceleration and try again?

**Comment by lllAlex2333** [comment]
Can i enable the 3D acceleration without a graphics card？

**Comment by alexballas** [comment]
> Can i enable the 3D acceleration without a graphics card？

As long as you have a monitor connected to your PC, then you have a graphics card. The 3D acceleration is emulated, so in theory it should work just fine.
