### ISSUE TITLE
m3u links support

### ISSUE THREAD

**Issue by erxson** [alexballas/go2tv#84]
It would great to play links from this repo https://github.com/Free-TV/IPTV
like .m3u8 or .mpd streams

I already tried to stream one of those urls, but my tv says that "format is not supported"

**Comment by Ilyaxin** [comment]
good idea!

**Comment by alexballas** [comment]
Hello, unfortunately this is not something we can control in Go2TV.

Let me explain: All Go2TV does is to point a specific media file to a device (media renderer) and it's up to the device to decide how to handle it. To my knowledge, there is no media renderer that can handle files like .m3u8 and I tested a lot. Go2TV is based on a subset of the DLNA protocol which is considered "legacy protocol" by many vendors. As such, any adaptation of that protocol tends to be very bare bones. 

Formats like m3u8 are more complex and I doubt the vendors would put the effort to integrate it with DNLA.

So for the reasons above, I'll close this ticket.

**Comment by alexballas** [comment]
This is now supported when casting to Chromecast devices.
