### ISSUE TITLE
docker build fails - missing net/netip

### ISSUE THREAD

**Issue by fergald** [alexballas/go2tv#89]
```
/go/pkg/mod/github.com/fredbi/uri@v1.1.0/uri.go:19:2: package net/netip is not in GOROOT (/usr/local/go/src/net/netip)
make: *** [Makefile:5: build] Error 1
```

netip does not show in the list of packages that get downloaded by docker.

**Comment by alexballas** [comment]
Hello @fergald ,
Thanks for raising this. It seems that I forgot to update the Go docker image with the latest versions that introduced net/netip. You can fix this by replacing the first line of the Dockerfile with `FROM golang:1.23`

**Comment by alexballas** [comment]
https://github.com/alexballas/go2tv/commit/ee1b6c8f702ac4f0a94c6eee3d620c101e3e9725

**Comment by fergald** [comment]
Thanks. Built for me.

**Comment by sunhaox** [comment]
Hi @fergald , can you find devices in container? can you share the docker run command? Thanks.

**Comment by fergald** [comment]
I don't think I managed to get this to work. I didn't spend any time trying to debug but I guess container might be a factor.

**Comment by alexballas** [comment]
Check my comment here on how to run it from docker
https://github.com/alexballas/go2tv/issues/93#issuecomment-2433475693

**Comment by alexballas** [comment]
Update docker documentation -> https://github.com/alexballas/go2tv/tree/devel 
resolving
