### ISSUE TITLE
musl support? openwrt support?

### ISSUE THREAD

**Issue by CCCAUCHY** [alexballas/go2tv#92]
`-bash: /tmp/tmp/go2tv: cannot execute binary file: Exec format error`

**Comment by alexballas** [comment]
Hello,

The Go2TV version with the GUI option would not work in openwrt due to the various dependencies. What you could do however is use the non-gui version which I call "go2tv-lite" and compile it for openwrt.  
Steps
```
$ git clone git@github.com:alexballas/go2tv.git
$ cd go2tv/cmd/go2tv-lite/
$ GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build
$ file go2tv-lite 
go2tv-lite: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, Go BuildID=YUZlhcoZBGI8TmO6c2xo/UZYmeLR9KJwiBQ94lQAr/10F69wnmxGHP5LxlJn12/lmaUQ1_xuXo2FI1yf2E4, with debug_info, not stripped
```
Let me know if you have any questions

**Comment by CCCAUCHY** [comment]
> Hello,
> 
> The Go2TV version with the GUI option would not work in openwrt due to the various dependencies. What you could do however is use the non-gui version which I call "go2tv-lite" and compile it for openwrt. Steps
> 
> ```
> $ git clone git@github.com:alexballas/go2tv.git
> $ cd go2tv/cmd/go2tv-lite/
> $ GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build
> $ file go2tv-lite 
> go2tv-lite: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, Go BuildID=YUZlhcoZBGI8TmO6c2xo/UZYmeLR9KJwiBQ94lQAr/10F69wnmxGHP5LxlJn12/lmaUQ1_xuXo2FI1yf2E4, with debug_info, not stripped
> ```
> 
> Let me know if you have any questions

I need arm64. But I need mipsle too. How many flags can I choose?

**Comment by alexballas** [comment]
Hello, 

The Go compilers support the following instruction sets:

amd64, 386
- The x86 instruction set, 64- and 32-bit.

arm64, arm
- The ARM instruction set, 64-bit (AArch64) and 32-bit.

loong64
- The 64-bit LoongArch instruction set.

mips64, mips64le, mips, mipsle
- The MIPS instruction set, big- and little-endian, 64- and 32-bit.

ppc64, ppc64le
- The 64-bit PowerPC instruction set, big- and little-endian.

riscv64
- The 64-bit RISC-V instruction set.

s390x
- The IBM z/Architecture.

wasm

**Comment by CCCAUCHY** [comment]
thanks
