### ISSUE TITLE
The Obtanium can't find zipped apk file. Please, can you provide the .apk instead of .zip

### ISSUE THREAD

**Issue by ludrol** [alexballas/go2tv#96]
Obtanium an app that let's you download and auto update other apps from github and other sources doesn't show zipped files https://www.github.com/ImranR98/Obtainium/issues/983 

Could you provide the apk file as is in releases tab, so Obtanium can see it?

(Thanks a lot for this piece of software as it enabled me to watch a movie with subtittles on a TV)

**Comment by alexballas** [comment]
Hello! I just uploaded :) Closing this.

**Comment by alexballas** [comment]
btw the wrong version that appears as 0.0.1 should be fixed in the upcoming version 1.18.0
